update: Talking to vic from terminal via picocom
mrshu/vic pull request #33
Opened 2016-05-30 15:54 UTC by vargac

* Add a simple shell script for properly setting picocom arguments
* Edit arduino example a bit. Print helps at first, remove explicitly printing
  prompt (vic already does it by itself). After backspace (moving cursor one
  step back) print space (remove last typed character) and again move cursor
  back
* Add simple arduino sketch echoing sent characters in integer form

Signed-off-by: vargac <simon.varga123@gmail.com>

2016-06-11 08:57 UTC, Adman commented
@vargac please resolve those branch conflicts

2016-06-20 13:03 UTC, vargac commented
@Adman Done

2017-04-01 13:29 UTC, mrshu requested changes
@vargac I only found a few nitpicks. Once you resolve them (or decide that they are not worth resolving), feel free to merge this.

2017-04-01 13:29 UTC, mrshu commented on examples/vic_basic/vic_basic.ino
> +   feed) or vic-picocom (find it in shell/) for talking to vic */
@vargac it may be better to say `which can be found in shell/` rather than `find it in shell/`

2017-04-01 13:29 UTC, mrshu commented on examples/vic_basic/vic_basic.ino
> +        if (c == '\b') Serial.print(" \b");
@vargac Just out of curiosity, why is the space necessary? In other words, I understand the `\b` but I do not quite get ` \b`.

2017-04-01 16:11 UTC, vargac commented on examples/vic_basic/vic_basic.ino
> +   feed) or vic-picocom (find it in shell/) for talking to vic */
OK, changed

2017-04-01 16:24 UTC, vargac commented on examples/vic_basic/vic_basic.ino
> +        if (c == '\b') Serial.print(" \b");
@mrshu Echo character is on, so when user types backspace, cursor in picocom will move backward, then we will send these characters from arduino to delete last character on users's screen (overwrite with space) and then move backward agan

2017-04-01 18:09 UTC, mrshu commented on examples/vic_basic/vic_basic.ino
> +        if (c == '\b') Serial.print(" \b");
@vargac ah, nice, that makes a lot of sense!

2017-04-01 18:10 UTC, merged